bookers/config/routes.rb
Rails.application.routes.draw do
  resources :books
  root to: "homes#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end
  
  def new
  end

  def index
    @book=Book.new
    @books=Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def create
    
    @book = Book.new(book_params)
    if @book.save
      flash[:notice]="Book was successfully created."
      redirect_to book_path(@book.id)
    else @books = Book.all
      render :index
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to "/books/#{@book.id}"
    else 
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] ="Book was successfully deleted."
    redirect_to "/books"
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:
    <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
<% end %>
<%=form_with model: @book, url: "/books/#{@book.id}", method: :patch do |f|%>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_field :body %>
    <div class="block">
        <%= f.submit "Update Book"%>
    </div>
<%end%>
<p><%=link_to"Show","/books/#{@book.id}"%>|<%=link_to"Back","/books"%></p>

bookers/app/views/books/index.html.erb
<body>
   <%=flash[:notice]%>
  <h1>Books</h1>

  <table>
    
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
      </tr>
    </thead>
    
    <tbody>
      <% @books.each do |book|%>
        <tr>
          <td><%= book.title%></td>
          <td><%= book.body%></td>
          <td><%=link_to "Show","/books/#{book.id}"%></td>
          <td><%=link_to "Edit","/books/#{book.id}/edit"%></td>
          <td><%=link_to "Destroy","/books/#{book.id}", method: :delete, "data-confirm" => "本当に削除しますか？"%></td>
        </tr>
      <% end %>
    </tbody>
    
  </table>
 
  <h2>New book</h2>
  <% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  <%= form_with model: @book, url: "/books", method: :post do |f| %>
    <h4> Title </h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    
    <div class="block"><%= f.submit "Create Book"%></div>
    
  <% end %>
</body>

bookers/app/views/books/show.html.erb
<%=flash[:notice]%>
<p>Title:<%=@book.title%></p>

<p>Body:<%=@book.body%></p>  


<div class =show_p>
  <p><%= link_to "Edit","/books/#{@book.id}/edit" %>&nbsp;|&nbsp;<%= link_to "Back","/books" %></p>
</div>

bookers/app/views/homes/top.html.erb
<h1 class="header">ようこそBookersへ！</h1>

<p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます。</p>

<%= link_to "start", books_path, class:"link"%>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>